#!/usr/bin/env bash
set -eu

cd "$(dirname "$0")/../.." || exit 1

if [ -f .git/hooks/pre-commit ]; then
    .git/hooks/pre-commit "$@"
fi

TEST_PARALLELISM="$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 1)"
export TEST_PARALLELISM

if [ ! -n "${ELASH_PRECOMMIT_NO_UNIT:-}" ]; then make unit-test &>/dev/null; fi
if [ ! -n "${ELASH_PRECOMMIT_NO_E2E:-}" ];  then make test-e2e >/dev/null;   fi
