name: CI on Linux ARM64

on:
  pull_request:
    branches:
      - '**'

jobs:
  run-ci:
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/${{ github.repository_owner }}/elash-ci-arm64:latest

    steps:
      - name: Checkout repository
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git clone https://github.com/${{ github.repository }}.git .
          git checkout ${{ github.sha }}

      - name: Build
        run: make libelash-static elc -j$(nproc)

      - name: Unit tests
        run: make unit-test

      - name: End‑to‑End tests
        run: make test-e2e

