name: CI on Linux ARM64

permissions:
  contents: read

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  run-ci:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Cache ccache
        uses: actions/cache@v6
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-${{ runner.arch }}-ccache-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-ccache-${{ github.ref_name }}-
            ${{ runner.os }}-${{ runner.arch }}-ccache-

      - name: Run CI inside container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:${{ github.workspace }}" \
            -v "${HOME}/.cache/ccache:/ccache" \
            -w "${{ github.workspace }}" \
            -e CC="ccache cc" \
            -e CCACHE_DIR="/ccache" \
            "ghcr.io/${{ github.repository_owner }}/elash-ci-arm64:latest" \
            sh -c "ccache -z && make libelash-static elc -j\$(nproc) && ccache -s && make unit-test && make test-e2e"

