name: Build X64 CI image

permissions:
  contents: read
  packages: write

on:
  push:
    paths:
      - '.github/docker/x64/Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .github/docker/x64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/elash-ci-x64:latest

